# Generated by Django 2.2.15 on 2020-08-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200806_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kjhkj', models.BigIntegerField()),
            ],
        ),
    ]
