# Generated by Django 2.2.15 on 2020-08-06 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200806_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtext',
            old_name='title22',
            new_name='nameChanged',
        ),
    ]
