# Generated by Django 2.2.15 on 2020-08-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200806_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body2',
            new_name='body212',
        ),
    ]
