# Generated by Django 2.2.15 on 2020-08-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200806_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtext',
            old_name='title1234',
            new_name='title1234ds',
        ),
    ]
