# Generated by Django 2.2.15 on 2020-08-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200806_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtext',
            name='title1234ds',
            field=models.BinaryField(blank=True, max_length=150, null=True),
        ),
    ]
